twist_mux:
  ros__parameters:
    locks:
      pause_navigation:
        topic   : pause_nav
        timeout : 0.0
        priority: 75

      stop_all:
        topic   : stop_all
        timeout : 0.0
        priority: 100

      pause_manual:
        topic   : pause_man
        timeout : 0.0
        priority: 175

      